# Generated by Django 5.1.2 on 2024-10-18 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(limit_choices_to={'category': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_toppings', to='pizzaapi.product')),
                ('topping', models.ForeignKey(limit_choices_to={'category': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='topping_pizzas', to='pizzaapi.product')),
            ],
            options={
                'unique_together': {('pizza', 'topping')},
            },
        ),
    ]
